[build]
  command = "pnpm install && pnpm install --platform=linux --arch=x64 sharp && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.9.0"
  PNPM_VERSION = "10.15.1"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  NETLIFY_USE_PNPM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless", "pg-native"]
  included_files = ["dist/**/*", "src/**/*"]

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
