[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_VERSION = "10.9.1"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  SHARP_SKIP_PLATFORM_LIBVIPS = "1"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
