// This file is auto-generated by Payload
// Do not edit this file directly

export interface Config {
  collections: {
    users: User
    media: Media
    seasons: Season
    locations: Location
    officials: Official
    conferences: Conference
    divisions: Division
    teams: Team
    sessions: Session
    games: Game
    players: Player
  }
  globals: {}
}

export interface User {
  id: string
  email: string
  role: 'admin' | 'user'
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: string
  alt: string
  caption?: string | null
  tags?: {
    tag?: string | null
    id?: string | null
  }[]
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}

export interface Season {
  id: string
  name: string
  type: 'regular' | 'summer' | 'tournament' | 'preseason'
  year: number
  startDate: string
  endDate: string
  registrationDeadline?: string | null
  isActive?: boolean | null
  status: 'planning' | 'registration' | 'active' | 'completed' | 'archived'
  maxTeamsPerDivision?: number | null
  gameFormat?: {
    periodLength?: number | null
    numberOfPeriods?: number | null
    overtimeLength?: number | null
  }
  locations?: (string | Location)[] | null
  officials?: (string | Official)[] | null
  rules?: any | null
  updatedAt: string
  createdAt: string
}

export interface Location {
  id: string
  name: string
  address: string
  city: string
  state: 'CA' | 'TX' | 'NY' | 'FL' | 'IL' | 'PA' | 'OH' | 'GA' | 'NC' | 'MI'
  zipCode: string
  coordinates?: {
    latitude?: number | null
    longitude?: number | null
  }
  capacity?: number | null
  courts?: {
    courtName: string
    courtType: 'full' | 'half' | 'practice'
    isAvailable?: boolean | null
    id?: string | null
  }[]
  facilities?: {
    facility:
      | 'parking'
      | 'concessions'
      | 'restrooms'
      | 'lockers'
      | 'scoreboards'
      | 'sound'
      | 'streaming'
      | 'accessible'
    id?: string | null
  }[]
  contactInfo?: {
    facilityManager?: string | null
    phone?: string | null
    email?: string | null
    website?: string | null
  }
  availability?: {
    dayOfWeek: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'
    openTime: string
    closeTime: string
    id?: string | null
  }[]
  pricing?: {
    hourlyRate?: number | null
    gameRate?: number | null
    notes?: string | null
  }
  isActive?: boolean | null
  updatedAt: string
  createdAt: string
}

export interface Official {
  id: string
  name: string
  email: string
  phone?: string | null
  emergencyContact?: {
    name?: string | null
    phone?: string | null
    relationship?: string | null
  }
  certificationLevel: 'trainee' | 'certified' | 'advanced' | 'master'
  certifications?: {
    certificationName: string
    issuedDate: string
    expirationDate: string
    issuingOrganization: string
    certificationNumber?: string | null
    id?: string | null
  }[]
  specialties?: {
    specialty:
      | 'youth'
      | 'high-school'
      | 'adult-rec'
      | 'tournament'
      | 'referee'
      | 'scorekeeper'
      | 'clock'
    id?: string | null
  }[]
  availability?: {
    dayOfWeek?:
      | 'monday'
      | 'tuesday'
      | 'wednesday'
      | 'thursday'
      | 'friday'
      | 'saturday'
      | 'sunday'
      | null
    timeSlot?: 'morning' | 'afternoon' | 'evening' | 'all-day' | null
    id?: string | null
  }[]
  paymentInfo?: {
    hourlyRate?: number | null
    gameRate?: number | null
    paymentMethod?: 'check' | 'cash' | 'direct-deposit' | null
  }
  stats?: {
    gamesOfficiated?: number | null
    seasonsWorked?: number | null
    rating?: number | null
  }
  isActive?: boolean | null
  updatedAt: string
  createdAt: string
}

export interface Conference {
  id: string
  name: string
  season: string | Season
  description?: string | null
  divisionCount?: number | null
  commissioner?: {
    name?: string | null
    email?: string | null
    phone?: string | null
  }
  updatedAt: string
  createdAt: string
}

export interface Division {
  id: string
  name: string
  conference: string | Conference
  season: string | Season
  ageGroup: 'youth' | 'middle' | 'high-school' | 'adult-rec' | 'senior'
  skillLevel?: 'beginner' | 'intermediate' | 'advanced' | 'elite' | null
  teamLimits?: {
    maxTeams?: number | null
    minTeams?: number | null
    currentTeams?: number | null
  }
  schedule?: {
    gamesPerTeam?: number | null
    playoffTeams?: number | null
    regularSeasonWeeks?: number | null
  }
  description?: string | null
  updatedAt: string
  createdAt: string
}

export interface Team {
  id: string
  name: string
  shortName?: string | null
  logo?: string | Media | null
  location?: {
    city: string
    region?: string | null
    homeVenue?: string | Location | null
  }
  colors?: {
    primary: string
    secondary?: string | null
    accent?: string | null
  }
  division: string | Division
  season: string | Season
  headCoach: string
  staff?: {
    name: string
    role: 'head-coach' | 'assistant-coach' | 'manager' | 'trainer' | 'volunteer'
    email?: string | null
    phone?: string | null
    certifications?: {
      certification?: string | null
      expirationDate?: string | null
      id?: string | null
    }[]
    backgroundCheckDate?: string | null
    id?: string | null
  }[]
  contacts?: {
    name: string
    role: 'manager' | 'parent' | 'representative' | 'emergency'
    email: string
    phone: string
    isPrimary?: boolean | null
    id?: string | null
  }[]
  roster?: (string | Player)[] | null
  stats?: {
    wins?: number | null
    losses?: number | null
    ties?: number | null
    pointsFor?: number | null
    pointsAgainst?: number | null
    gamesPlayed?: number | null
  }
  currentRecord?: string | null
  status?: 'active' | 'inactive' | 'pending' | 'suspended' | null
  registrationInfo?: {
    registrationDate?: string | null
    feePaid?: boolean | null
    documentsSubmitted?: boolean | null
    rosterSubmitted?: boolean | null
  }
  notes?: string | null
  updatedAt: string
  createdAt: string
}

export interface Session {
  id: string
  name: string
  type: 'regular' | 'playoffs' | 'championship' | 'tournament' | 'preseason' | 'allstar'
  season: string | Season
  divisions?: (string | Division)[] | null
  startDate: string
  endDate: string
  registrationDeadline?: string | null
  format?: {
    roundRobin?: boolean | null
    singleElimination?: boolean | null
    doubleElimination?: boolean | null
  }
  description?: string | null
  isActive?: boolean | null
  updatedAt: string
  createdAt: string
}

export interface Game {
  id: string
  gameNumber?: number | null
  session: string | Session
  season: string | Season
  division: string | Division
  homeTeam: string | Team
  awayTeam: string | Team
  gameDate: string
  gameTime: string
  location: string | Location
  venue: string
  assignedOfficials?: (string | Official)[] | null
  status:
    | 'scheduled'
    | 'in-progress'
    | 'halftime'
    | 'final'
    | 'cancelled'
    | 'postponed'
    | 'forfeited'
  score?: {
    homeScore?: number | null
    awayScore?: number | null
    periods?: {
      period: number
      homeScore?: number | null
      awayScore?: number | null
      id?: string | null
    }[]
    overtime?: boolean | null
  }
  gameStats?: {
    attendance?: number | null
    weatherConditions?: string | null
    technicalFouls?: number | null
    ejections?: number | null
  }
  gameTitle?: string | null
  notes?: string | null
  updatedAt: string
  createdAt: string
}

export interface Player {
  id: string
  name: string
  firstName: string
  lastName: string
  team: string | Team
  position: 'PG' | 'SG' | 'SF' | 'PF' | 'C' | 'G' | 'F'
  jerseyNumber: number
  personalInfo?: {
    dateOfBirth?: string | null
    gradYear: number
    height?: string | null
    weight?: number | null
    hometown: string
    region: string
  }
  photo?: string | Media | null
  contact?: {
    email: string
    phone?: string | null
    parentEmail?: string | null
    emergencyContact?: {
      name?: string | null
      phone?: string | null
      relationship?: string | null
    }
  }
  seasonStats?: {
    gamesPlayed?: number | null
    points?: number | null
    rebounds?: number | null
    assists?: number | null
    steals?: number | null
    blocks?: number | null
    turnovers?: number | null
    fouls?: number | null
    minutes?: number | null
    fieldGoalsMade?: number | null
    fieldGoalsAttempted?: number | null
    threePointersMade?: number | null
    threePointersAttempted?: number | null
    freeThrowsMade?: number | null
    freeThrowsAttempted?: number | null
  }
  careerStats?: {
    season: string | Season
    team: string | Team
    stats?: {
      gamesPlayed?: number | null
      points?: number | null
      rebounds?: number | null
      assists?: number | null
      fieldGoalPercentage?: number | null
    }
    id?: string | null
  }[]
  achievements?: {
    award: string
    season?: string | Season | null
    description?: string | null
    dateAwarded?: string | null
    id?: string | null
  }[]
  media?: {
    highlightVideos?: {
      title: string
      url: string
      platform?: 'youtube' | 'hudl' | 'vimeo' | 'other' | null
      id?: string | null
    }[]
    socialMedia?: {
      instagram?: string | null
      twitter?: string | null
      tiktok?: string | null
    }
  }
  eligibility?: {
    isEligible?: boolean | null
    academicStanding?: 'good' | 'probation' | 'ineligible' | null
    medicalClearance?: boolean | null
    insuranceOnFile?: boolean | null
  }
  notes?: string | null
  updatedAt: string
  createdAt: string
}

export type PayloadRequest = any
export type PayloadResponse = any
export type PayloadNext = any
